In [5]:
import pandas as pd
import numpy as np
from typing import List, Tuple
import math




In [6]:

Vector = List[float]
def standard_deviation(xs: List[float]) -> float:
  """The standard deviation is the square root of the variance"""
  return math.sqrt(variance(xs))

def dot(v: Vector, w: Vector) -> float:
  """Computes v_1 * w_1 + ... + v_n * w_n"""
  assert len(v) == len(w), "vectors must be same length"

  return sum(v_i * w_i for v_i, w_i in zip(v, w))

def covariance(xs: List[float], ys: List[float]) -> float:
  assert len(xs) == len(ys), "xs and ys must have same number of elements"

  return dot(de_mean(xs), de_mean(ys)) / (len(xs) - 1)

def correlation(xs: List[float], ys: List[float]) -> float:
  """Measures how much xs and ys vary in tandem about their means"""
  stdev_x = standard_deviation(xs)
  stdev_y = standard_deviation(ys)
  if stdev_x > 0 and stdev_y > 0:
    return covariance(xs, ys) / stdev_x / stdev_y
  else:
    return 0    # if no variation, correlation is zero


def predict(alpha: float, beta: float, x_i: float) -> float:
  return beta * x_i + alpha

def error(alpha: float, beta: float, x_i: float, y_i: float) -> float:
  """
  The error from predicting beta * x_i + alpha
  when the actual value is y_i
  """
  return predict(alpha, beta, x_i) - y_i

def mean(xs: List[float]) -> float:
  return sum(xs) / len(xs)

def de_mean(xs: List[float]) -> List[float]:
  """Translate xs by subtracting its mean (so the result has mean 0)"""
  x_bar = mean(xs)
  return [x - x_bar for x in xs]

def sum_of_sqerrors(alpha: float, beta: float, x: Vector, y: Vector) -> float:
  return sum(error(alpha, beta, x_i, y_i) ** 2
             for x_i, y_i in zip(x, y))

def sum_of_squares(v: Vector) -> float:
  """Returns v_1 * v_1 + ... + v_n * v_n"""
  return dot(v, v)

def variance(xs: List[float]) -> float:
  """Almost the average squared deviation from the mean"""
  assert len(xs) >= 2, "variance requires at least two elements"

  n = len(xs)
  deviations = de_mean(xs)
  return sum_of_squares(deviations) / (n - 1)

In [7]:
def least_squares_fit(x: Vector, y: Vector) -> Tuple[float, float]:
  """
  Given two vectors x and y,
  find the least-squares values of alpha and beta
  """
  beta = correlation(x, y) * standard_deviation(y) / standard_deviation(x)
  alpha = mean(y) - beta * mean(x)
  return alpha, beta


In [8]:
x = [i for i in range(-100, 110, 10)]
y = [3 * i - 5 for i in x]

In [9]:
# num_friends = [100.0,49,41,40,25,21,21,19,19,18,18,16,15,15,15,15,14,14,13,13,13,13,12,12,11,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,8,8,8,8,8,8,8,8,8,8,8,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
# daily_minutes = [1,68.77,51.25,52.08,38.36,44.54,57.13,51.4,41.42,31.22,34.76,54.01,38.79,47.59,49.1,27.66,41.03,36.73,48.65,28.12,46.62,35.57,32.98,35,26.07,23.77,39.73,40.57,31.65,31.21,36.32,20.45,21.93,26.02,27.34,23.49,46.94,30.5,33.8,24.23,21.4,27.94,32.24,40.57,25.07,19.42,22.39,18.42,46.96,23.72,26.41,26.97,36.76,40.32,35.02,29.47,30.2,31,38.11,38.18,36.31,21.03,30.86,36.07,28.66,29.08,37.28,15.28,24.17,22.31,30.17,25.53,19.85,35.37,44.6,17.23,13.47,26.33,35.02,32.09,24.81,19.33,28.77,24.26,31.98,25.73,24.86,16.28,34.51,15.23,39.72,40.8,26.06,35.76,34.76,16.13,44.04,18.03,19.65,32.62,35.59,39.43,14.18,35.24,40.13,41.82,35.45,36.07,43.67,24.61,20.9,21.9,18.79,27.61,27.21,26.61,29.77,20.59,27.53,13.82,33.2,25,33.1,36.65,18.63,14.87,22.2,36.81,25.53,24.62,26.25,18.21,28.08,19.42,29.79,32.8,35.99,28.32,27.79,35.88,29.06,36.28,14.1,36.63,37.49,26.9,18.58,38.48,24.48,18.95,33.55,14.24,29.04,32.51,25.63,22.22,19,32.73,15.16,13.9,27.2,32.01,29.27,33,13.74,20.42,27.32,18.23,35.35,28.48,9.08,24.62,20.12,35.26,19.92,31.02,16.49,12.16,30.7,31.22,34.65,13.13,27.51,33.2,31.57,14.1,33.42,17.44,10.12,24.42,9.82,23.39,30.93,15.03,21.67,31.09,33.29,22.61,26.89,23.48,8.38,27.81,32.35,23.84]
# outlier = num_friends.index(100)    # index of outlier
#
# num_friends_good = [x
#                     for i, x in enumerate(num_friends)
#                     if i != outlier]
#
# daily_minutes_good = [x
#                       for i, x in enumerate(daily_minutes)
#                       if i != outlier]

In [10]:
# alpha, beta = least_squares_fit(num_friends_good, daily_minutes_good)


In [11]:
def total_sum_of_squares(y: Vector) -> float:
  """the total squared variation of y_i's from their mean"""
  return sum(v ** 2 for v in de_mean(y))

def r_squared(alpha: float, beta: float, x: Vector, y: Vector) -> float:
  """
  the fraction of variation in y captured by the model, which equals
  1 - the fraction of variation in y not captured by the model
  """
  return 1.0 - (sum_of_sqerrors(alpha, beta, x, y) /
                total_sum_of_squares(y))

In [12]:
# change the data used

# import JSON dataset using panda
dataset = pd.read_json('tenant_performance.json')
avg_visit_duration = dataset['avg_visit_duration']
revenue = dataset['revenue']

alpha, beta = least_squares_fit(avg_visit_duration, revenue)

In [13]:
alpha

-45.561551599912406

In [14]:
beta

3.8157701566146787

In [15]:
def predict(alpha: float, beta: float, x_i: float) -> float:
  return beta * x_i + alpha

In [16]:
# predict(alpha, beta, 10)

In [17]:
# Predict the revenue with avg_visit_duration = 10
print("predict:")
print(predict(alpha, beta, 10))

predict:
-7.403850033765622


In [18]:
# Predict the revenue with avg_visit_duration = 30
print("predict:")
print(predict(alpha, beta, 30))

predict:
68.91155309852796


In [19]:
from numpy import subtract


def scalar_multiply(c: float, v: Vector) -> Vector:
  """Multiplies every element by c"""
  return [c * v_i for v_i in v]

def add(v: Vector, w: Vector) -> Vector:
  """Adds corresponding elements"""
  assert len(v) == len(w), "vectors must be the same length"

  return [v_i + w_i for v_i, w_i in zip(v, w)]

def gradient_step(v: Vector, gradient: Vector, step_size: float) -> Vector:
  """Moves `step_size` in the `gradient` direction from `v`"""
  assert len(v) == len(gradient)
  step = scalar_multiply(step_size, gradient)
  return add(v, step)

def sum_of_squares(v: Vector) -> float:
  """Returns v_1 * v_1 + ... + v_n * v_n"""
  return dot(v, v)

assert sum_of_squares([1, 2, 3]) == 14  # 1 * 1 + 2 * 2 + 3 * 3

import math

def magnitude(v: Vector) -> float:
  """Returns the magnitude (or length) of v"""
  return math.sqrt(sum_of_squares(v))   # math.sqrt is square root function

assert magnitude([3, 4]) == 5

def squared_distance(v: Vector, w: Vector) -> float:
  """Computes (v_1 - w_1) ** 2 + ... + (v_n - w_n) ** 2"""
  return sum_of_squares(subtract(v, w))

In [31]:
import random
import tqdm

num_epochs = 20000
learning_rate = 0.0000001

random.seed(0)

guess = [random.random(), random.random()]  # choose random value to start


with tqdm.trange(num_epochs) as t:
  for _ in t:
    alpha, beta = guess

# for x_i, y_i in zip(num_friends_good,
#                     daily_minutes_good))
# for x_i, y_i in zip(avg_visit_duration,
#                     revenue))
    # Partial derivative of loss with respect to alpha
    grad_a = sum(2 * error(alpha, beta, x_i, y_i)
                 for x_i, y_i in zip(avg_visit_duration,
                                     revenue))

    # Partial derivative of loss with respect to beta
    grad_b = sum(2 * error(alpha, beta, x_i, y_i) * x_i
                 for x_i, y_i in zip(avg_visit_duration,
                                     revenue))

    # Compute loss to stick in the tqdm description
    loss = sum_of_sqerrors(alpha, beta,
                           avg_visit_duration, revenue)
    t.set_description(f"loss: {loss:.3f}")

    # Finally, update the guess
    guess = gradient_step(guess, [grad_a, grad_b], -learning_rate)

loss: 102106918.815: 100%|██████████| 20000/20000 [02:45<00:00, 120.79it/s]


In [32]:
alpha

-45.56154997830489

In [33]:
beta

3.8157700795538583

In [34]:
guess

[-45.561549979696544, 3.8157700796199916]

In [2]:
# Tensorflow
import tensorflow as tf

In [41]:

import random
import tqdm

num_epochs = 10000
random.seed(0)

guess = [random.random(), random.random()]  # choose random value to start

learning_rate = 0.00001

with tqdm.trange(num_epochs) as t:
  for _ in t:
    alpha, beta = guess

    # Partial derivative of loss with respect to alpha
    grad_a = sum(2 * error(alpha, beta, x_i, y_i)
                 for x_i, y_i in zip(avg_visit_duration,
                                     revenue))

    # Partial derivative of loss with respect to beta
    grad_b = sum(2 * error(alpha, beta, x_i, y_i) * x_i
                 for x_i, y_i in zip(avg_visit_duration,
                                     revenue))

    # Original Tensorflow gradient clip
    # ClipByValue(
    #   const ::tensorflow::Scope & scope,
    # ::tensorflow::Input t,
    # ::tensorflow::Input clip_value_min,
    # ::tensorflow::Input clip_value_max
    # )
    # https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/clip-by-value
    grad_a = tf.clip_by_value(grad_a, clip_value_min=-2.0, clip_value_max=2.0)
    grad_b = tf.clip_by_value(grad_b, clip_value_min=-2.0, clip_value_max=2.0)

    # Compute loss to stick in the tqdm description
    loss = sum_of_sqerrors(alpha, beta,
                           avg_visit_duration, revenue)
    t.set_description(f"loss: {loss:.3f}")

    # Finally, update the guess
    guess = gradient_step(guess, [grad_a, grad_b], -learning_rate)


loss: 113224728.000:   0%|          | 5/10000 [00:20<11:16:56,  4.06s/it]


KeyboardInterrupt: 

In [22]:
alpha

<tf.Tensor: shape=(), dtype=float32, numpy=0.8443618>

In [23]:
beta

<tf.Tensor: shape=(), dtype=float32, numpy=0.7580145>

In [24]:
guess

[<tf.Tensor: shape=(), dtype=float32, numpy=0.8443618>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.7580145>]

In [25]:
# Test Cuda

loss: 4642892657.615: 100%|██████████| 10000/10000 [01:19<00:00, 125.66it/s]


In [4]:
 physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))
print(tf.version)

from tensorflow.python.client import device_lib

def get_available_devices():
  local_device_protos = device_lib.list_local_devices()
  return [x.name for x in local_device_protos]

print(get_available_devices())

# Note cuDDN not detected?
# only showing ['/device:CPU:0']

Num GPUs: 0
<module 'tensorflow._api.v2.version' from 'Z:\\Workshop\\Binus\\SEMESTER 6-1\\DSGithub\\datascience_course\\venv\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>
['/device:CPU:0']
